---
site_name: "205"
site_url: "https://kyongho2.github.io/"
docs_dir: "docs"
repo_url: https://github.com/kyongho2/kyongho2.github.io
repo_name: kyongho2/documentation
edit_uri: "edit/main/docs/"

theme:
  name: material
  custom_dir: theme
  icon:
    edit: material/pencil
  features:
    - content.action.edit
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
#  logo: assets/logo.png
#  favicon: assets/logo.png
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: black
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: black

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.tasklist
  - footnotes
  - def_list
  - meta

plugins:
  - search
  - awesome-pages
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - build: true
          default: true
          locale: en
          name: English
        - build: true
          default: false
          locale: ko
          name: 한국어
#  - git-revision-date-localized:
#      type: date
  - tags
  - privacy
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kyongho2
